# Generated by Django 3.2.4 on 2021-06-21 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_mechanicprofile_mechanic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to='tracker.driver'),
        ),
    ]
